# Generated by Django 4.0.3 on 2022-12-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_rename_vin_appointment_automobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appt_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='appt_time',
        ),
    ]
