# Generated by Django 4.0.3 on 2022-12-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_remove_appointment_appt_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='apt_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='apt_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appt_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appt_time',
            field=models.TimeField(null=True),
        ),
    ]
