# Generated by Django 4.0.3 on 2022-12-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_remove_appointment_apt_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appt_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appt_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='starts',
            field=models.DateTimeField(null=True),
        ),
    ]
